### ISSUE TITLE
Crashing?!?!

### ISSUE THREAD

**Issue by Ace8Underscore** [TerikKek/CousinWare#2]
Client doesnt load when i open it help???

**Comment by TerikKek** [comment]
IDK EITHER MAN IT KEEPS ON CRASHING FOR ME TOO

**Comment by Crystallinqq** [comment]
![image](https://user-images.githubusercontent.com/11377481/104973114-c98db680-59c1-11eb-9e60-6cf4efb5b375.png)
works for me :^)

**Comment by frosthead69** [comment]
cousin approved!1!
